algo: ddqn
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  batch_size: 64
  buffer_capacity: 256
  c_lr: 0.005
  epsilon: 0.2
  epsilon_end: 0.01
  gamma: 0.99
  given_net: false
  hidden_size: 64
  target_replace: 100
  marl: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 1
  learn_terminal: false
  max_episodes: 500
  render: false
  save_interval: 50
