algo: pg
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  batch_size: 64
  buffer_capacity: 256
  gamma: 0.99
  hidden_size: 64
  learn_terminal: true
  lr: 0.001
  marl: false
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 1000
  render: false
  save_interval: 100
